# Generated by Django 4.1.3 on 2022-12-24 06:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='Название')),
            ],
            options={
                'verbose_name': 'Группа',
                'verbose_name_plural': 'Группы',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='UserSendMessageInGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField(max_length=1200)),
                ('receiver_group', models.ManyToManyField(to='groups.group')),
                ('user_sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sender_group', to=settings.AUTH_USER_MODEL, verbose_name='От пользователя')),
            ],
            options={
                'verbose_name': 'Сообщение в группу',
                'verbose_name_plural': 'Сообщения в группу',
                'ordering': ['message'],
            },
        ),
    ]
